export const MetaSettings: {
  [key: string]: { maxValue: number; price: number; explanation: string };
} = {
  'Category visible': {
    maxValue: 1,
    price: 25,
    explanation: '<strong>Category visible:</strong><br/><br/>Shows the category for the word',
  },
  'Purge group 3': {
    maxValue: 4,
    price: 50,
    explanation:
      '<strong>Purge group 3:</strong><br/><br/>Removes unused letters from group 3:<br/>F, Y, W, V, K, X, Z, J, Q',
  },
  'Purge group 2': {
    maxValue: 3,
    price: 100,
    explanation:
      '<strong>Purge group 2:</strong><br/><br/>Removes unused letters from group 2:<br/>C, U, D, P, M, H, G, B',
  },
  'Purge group 1': {
    maxValue: 2,
    price: 250,
    explanation:
      '<strong>Purge group 1:</strong><br/><br/>Removes unused letters from group 1:<br/>E, A, R, I, O, T, N, S, L',
  },
  'Definition visible': {
    maxValue: 5,
    price: 500,
    explanation:
      '<strong>Definition visible:</strong><br/><br/>Shows (part of) the definition<br/><br/>Rank 1 shows every 5th word<br/>Rank 2 shows every 4th word<br/>Rank 3 shows every 3rd word<br/>Rank 4 shows every 2nd word<br/>Rank 5 shows the entire definition',
  },
  'Free letter': {
    maxValue: 1,
    price: 1000,
    explanation: '<strong>Free letter:</strong><br/><br/>Get a random free letter when starting a new word.',
  },
  'Remove clouds': {
    maxValue: 1,
    price: 2500,
    explanation:
      '<strong>Remove clouds:</strong><br/><br/>Removes the clouds around the word.<br/>Always see full length of the word.',
  },
};

export const KeyboardLayout: string[][] = [
  ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
  ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l'],
  ['z', 'x', 'c', 'v', 'b', 'n', 'm'],
];

//letterGroups are ordered by frequency of use in English
//https://en.wikipedia.org/wiki/Letter_frequency
export const LetterGroups: string[][] = [
  ['e', 'a', 'r', 'i', 'o', 't', 'n', 's', 'l'],
  ['c', 'u', 'd', 'p', 'm', 'h', 'g', 'b'],
  ['f', 'y', 'w', 'v', 'k', 'x', 'z', 'j', 'q'],
];

export const styledCategories = [
  '🧑‍🤝‍🧑 People and Relationships 💞',
  '🌿 Nature and Environment 🌍',
  '🫁 Body and Health 🩺',
  '🍕 Food and Drink 🥤',
  '🛠️ Objects and Tools 🧰',
  '🗺️ Places and Geography 🌆',
  '⏳ Time and Dates 📅',
  '😄 Emotions and States 🧠',
  '🎯 Activities and Leisure 🕹️',
  '🚶 Movement and Travel ✈️',
  '🗣️ Communication and Language ✍️',
  '💼 Work and Business 📈',
  '🏛️ Society and Politics 🗳️',
  '🔬 Science and Technology 🤖',
  '📏 Quantities and Measurements ⚖️',
  '🌌 Abstract Concepts 🧠',
  '🎨 Colors and Descriptions 🧵',
];

export const winMessages = [
  'Nice! 🎯',
  'Well done! 👏',
  'You nailed it! 🔨',
  'Boom! 💥',
  'Correct! ✅',
  'Great guess! 😎',
  'That’s it! 🎉',
  'Winner! 🏆',
  'Bingo! 🧠',
  'Hot damn! 🔥',
  'Crushed it! 💪',
  'Yes! 😁',
  'Smashed it! 🚀',
  'Bullseye! 🎯',
  'On fire! 🔥',
  'Bravo! 👏',
  'You beast! 🐾',
  'A+ work! 📘',
  'Legend! 👑',
  'Word wizard! ✨',
  'Sharp mind! 🧠',
  'Bang on! 🎯',
  'Epic win! 🏆',
  'Smart move! 🧠',
  'That’s the one! ✅',
  'Ooooh yes! 😏',
  'Busted it wide open! 💥',
  'Big brain! 🧠',
  'Too easy! 😎',
  'Gotcha! 🕵️',
  'Flex! 💪',
  "You're killing it! ☠️",
  'Nice work! 🔧',
  'Crackin’ job! 🧩',
  'Smooth! 😌',
  'Tidy guess! 🧼',
  'Sheer brilliance! 💡',
  'Top tier! 🏅',
  'Mad skills! 🌀',
  'Exacto! 🎯',
  'You got this! 💫',
  'Clean win! 🧽',
  'Sharp as ever! 🔪',
  'You rule! 👑',
  'Yup! 👍',
  'Pro move! 🎮',
  'Not bad! 😉',
  'Look at you! 🌟',
  'All day! ⏰',
  'Bangarang! 🛎️',
  'Boomshakalaka! 💣',
  'That was slick! 🧊',
  'One shot, one win! 🎯',
  'Feelin’ lucky? You should! 🍀',
  'Masterstroke! 🎨',
  'Overachiever! 🥇',
  'Zing! ⚡',
  'You’re a natural! 🌱',
  'Game on, game won! 🕹️',
  'Savage guess! 😤',
  'Mind = Blown 💥',
  'Big W! 🅆',
  'Crackshot! 🎯',
  'Stellar! 🌠',
  'No contest! 🥊',
  'Dead-on! 🧷',
  'Like a boss! 💼',
  'Clean sweep! 🧹',
  'Touché! 🗡️',
  'Prime pick! 🔍',
  'Unreal! 🎭',
  'You crushed that! 🍉',
  'Golden guess! 🥇',
  'Flawless! 🧼',
  'Too smooth! 🧊',
  'Sniped it! 🎯',
  'Goat level! 🐐',
  'Victory lap! 🏁',
  'The stuff of legends! 📖',
  'King/Queen move! 👑',
];
